include:
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@2.1.0
  - local: .gitlab/ci/molecule.yml
  - local: .gitlab/ci/terraform_test.yml
  - local: .gitlab/ci/packages.yml

stages:
  - test
  - terraform_test
  - ansible_molecule_test
  - upload
  - container_scan

#################################
##            RULES            ##
#################################

.on_merge_request_and_merged_events:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

.on_merge_request_and_merged_events_except_schedule_and_tag:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG'
      when: never
    - !reference [.on_merge_request_and_merged_events, rules]

.on_default_branch_except_schedule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.on_tag_events:
  rules:
    - if: "$CI_COMMIT_TAG"

#################################
##            SAST             ##
#################################

dependency-scanning:
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]

secret_detection:
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]
  allow_failure: false

container_scanning:
  stage: container_scan
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE
    CI_APPLICATION_TAG: dev
    GIT_STRATEGY: fetch
  rules:
    - !reference [.on_default_branch_except_schedule, rules]

kics-iac-sast:
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]
  allow_failure: false

#########################
##     Lint Checks     ##
#########################

check:terraform-fmt:
  stage: test
  image:
    name: "hashicorp/terraform"
    entrypoint: [""]
  before_script:
    - terraform version
  script:
    - terraform fmt -check -recursive -diff .
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]

check:tflint:
  stage: test
  image:
    name: ghcr.io/terraform-linters/tflint:latest
    entrypoint: [""]
  script:
    - cd terraform/modules
    - tflint -c "$PWD/../../.tflint.hcl" --recursive
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]

check:ansible-lint:
  stage: test
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - chmod 700 ansible
    - cd ansible
    - ansible-galaxy install -r requirements/ansible-galaxy-requirements.yml
    - pip install jmespath
    - ansible-lint
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]
  retry: 2

check:markdownlint:
  stage: test
  image:
    name: node:lts-alpine3.19
    entrypoint: [""]
  script:
    - npm add -g markdownlint markdownlint-cli
    - markdownlint *.md docs/*.md
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]

check:markdown-external-link-check:
  stage: test
  image:
    name: ghcr.io/tcort/markdown-link-check
    entrypoint: [""]
  script:
    - /src/markdown-link-check --quiet --config .markdown-link-check.json *.md docs/*.md
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]
  retry: 2

check:markdown-internal-link-check:
  stage: test
  image:
    name: lycheeverse/lychee:latest-alpine
    entrypoint: [""]
  needs: []
  script:
    - find . -type f -name "*.md" | xargs lychee --offline --no-progress --quiet --include-fragments
  rules:
    - !reference [
        .on_merge_request_and_merged_events_except_schedule_and_tag,
        rules,
      ]
  retry: 2
