# Cargo KConfig - KConfig interpreter, configurator and menu
# Copyright (C) 2022  Sjoerd van Leent
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

stages:
  - build
  - test

rust latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - find . -name "Cargo.toml" -type f -exec cargo test --verbose --manifest-path {} \;
    - cargo build --release
  artifacts:
    paths:
      - target/debug/cargo-kconfig
      - target/release/cargo-kconfig

rust nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - find . -name "Cargo.toml" -type f -exec cargo test --verbose --manifest-path {} \;
    - cargo build --release
  allow_failure: true

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
