---
include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

stages:
  - test

semgrep-sast:
  needs: []

secret_detection:
  needs: []
  before_script:
    - apk add --no-cache jq
  script:
    - |
      export SECRET_DETECTION_REPORT_FILE="gl-secret-detection-report.json"
      /analyzer run
      if [ -f "$SECRET_DETECTION_REPORT_FILE" ]; then
        if [ "$(jq ".vulnerabilities | length" $SECRET_DETECTION_REPORT_FILE)" -gt 0 ]; then
          echo "Vulnerabilities detected. Please analyze the artifact"
          echo "$SECRET_DETECTION_REPORT_FILE produced by the 'secret-detection' job."
          exit 80
        fi
      else
        echo "Artifact $SECRET_DETECTION_REPORT_FILE does not exist."
        echo "The 'secret-detection' job likely didn't create one. Hence, no evaluation can be performed."
      fi
      find .
